//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Eye
    {
        [DisplayName("會員帳號")]
        public string Account { get; set; }
        [DisplayName("左眼近視度數")]
        public double RightEyeMyopia { get; set; }
        [DisplayName("左眼閃光角度")]
        public double RightEyeAstigmaticAngel { get; set; }
        [DisplayName("左眼閃光度數")]
        public double RightEyeAstigmatic { get; set; }
        [DisplayName("右眼近視度數")]
        public double LeftEyeMyopia { get; set; }
        [DisplayName("右眼閃光角度")]
        public double LeftEyeAstigmaticAngel { get; set; }
        [DisplayName("右眼閃光度數")]
        public double LeftEyeAstigmatic { get; set; }
        [DisplayName("商品價格")]
        public double Price { get; set; }
        [DisplayName("鏡框總類")]
        public string FrameName { get; set; }
        [DisplayName("客戶下單時間")]
        public double MyTime { get; set; }
        [DisplayName("會員姓名")]
        public string Notes { get; set; }
    }
}
